### ISSUE TITLE
Support AWS CLI Nested Properties

### ISSUE THREAD

**Issue by KierranM** [a2ikm/aws_config#6]
Amazon in all their mighty wisdom decided that it would be a good idea to allow you to nest properties like so:

```
[default]
region=ap-southeast-2
s3=
    max_concurrent_requests=100101
    max_queue_size=20
```

While this is a pretty cool for not having to repeatedly type `s3_` in front of everything it completely goes against the INI file standard, and makes parsing it rather annoying. Even so, we should still support it.

**Comment by darrendao** [comment]
+1
